### ISSUE TITLE
你好，在wangeditor嵌入公式后出现菜单重复的问题

### ISSUE THREAD

**Issue by Joe4smu** [hansonGong/math-editor#2]
作者你好，我又来麻烦你了。用你的方法在wangeditor4集成公式后，第一次点击“公式”弹出框是正常的，公式等都可以输入，但第二次点击就出现菜单重复的问题，公式框显示异常，控制台提示如下：

```
formula-editor.min.js:1591 
        
       菜单名称重复:presets
_initMenuList @ formula-editor.min.js:1591
(匿名) @ formula-editor.min.js:1579
init @ formula-editor.min.js:1576
create @ formula-editor.min.js:1699
clickHandler @ formula-menu.conf.js:28
(匿名) @ wangEditor.min.js:1
formula-editor.min.js:1591 
        
       菜单名称重复:operators
_initMenuList @ formula-editor.min.js:1591
(匿名) @ formula-editor.min.js:1579
init @ formula-editor.min.js:1576
create @ formula-editor.min.js:1699
clickHandler @ formula-menu.conf.js:28
(匿名) @ wangEditor.min.js:1
formula-editor.min.js:1591 
        
       菜单名称重复:greekLetters
_initMenuList @ formula-editor.min.js:1591
(匿名) @ formula-editor.min.js:1579
init @ formula-editor.min.js:1576
create @ formula-editor.min.js:1699
clickHandler @ formula-menu.conf.js:28
(匿名) @ wangEditor.min.js:1
formula-editor.min.js:1591 
        
       菜单名称重复:inequation
_initMenuList @ formula-editor.min.js:1591
(匿名) @ formula-editor.min.js:1579
init @ formula-editor.min.js:1576
create @ formula-editor.min.js:1699
clickHandler @ formula-menu.conf.js:28
(匿名) @ wangEditor.min.js:1
formula-editor.min.js:1591 
        
       菜单名称重复:calculus
_initMenuList @ formula-editor.min.js:1591
(匿名) @ formula-editor.min.js:1579
init @ formula-editor.min.js:1576
create @ formula-editor.min.js:1699
clickHandler @ formula-menu.conf.js:28
(匿名) @ wangEditor.min.js:1
formula-editor.min.js:1591 
        
       菜单名称重复:arrows
_initMenuList @ formula-editor.min.js:1591
(匿名) @ formula-editor.min.js:1579
init @ formula-editor.min.js:1576
create @ formula-editor.min.js:1699
clickHandler @ formula-menu.conf.js:28
(匿名) @ wangEditor.min.js:1
formula-editor.min.js:1591 
        
       菜单名称重复:Trigonometric
_initMenuList @ formula-editor.min.js:1591
(匿名) @ formula-editor.min.js:1579
init @ formula-editor.min.js:1576
create @ formula-editor.min.js:1699
clickHandler @ formula-menu.conf.js:28
(匿名) @ wangEditor.min.js:1
formula-editor.min.js:1591 
        
       菜单名称重复:presets
_initMenuList @ formula-editor.min.js:1591
(匿名) @ formula-editor.min.js:1579
init @ formula-editor.min.js:1576
create @ formula-editor.min.js:1699
clickHandler @ formula-menu.conf.js:28
(匿名) @ wangEditor.min.js:1
formula-editor.min.js:1591 
        
       菜单名称重复:operators
_initMenuList @ formula-editor.min.js:1591
(匿名) @ formula-editor.min.js:1579
init @ formula-editor.min.js:1576
create @ formula-editor.min.js:1699
clickHandler @ formula-menu.conf.js:28
(匿名) @ wangEditor.min.js:1
formula-editor.min.js:1591 
        
       菜单名称重复:greekLetters
_initMenuList @ formula-editor.min.js:1591
(匿名) @ formula-editor.min.js:1579
init @ formula-editor.min.js:1576
create @ formula-editor.min.js:1699
clickHandler @ formula-menu.conf.js:28
(匿名) @ wangEditor.min.js:1
formula-editor.min.js:1591 
        
       菜单名称重复:inequation
_initMenuList @ formula-editor.min.js:1591
(匿名) @ formula-editor.min.js:1579
init @ formula-editor.min.js:1576
create @ formula-editor.min.js:1699
clickHandler @ formula-menu.conf.js:28
(匿名) @ wangEditor.min.js:1
formula-editor.min.js:1591 
        
       菜单名称重复:calculus
_initMenuList @ formula-editor.min.js:1591
(匿名) @ formula-editor.min.js:1579
init @ formula-editor.min.js:1576
create @ formula-editor.min.js:1699
clickHandler @ formula-menu.conf.js:28
(匿名) @ wangEditor.min.js:1
formula-editor.min.js:1591 
        
       菜单名称重复:arrows
_initMenuList @ formula-editor.min.js:1591
(匿名) @ formula-editor.min.js:1579
init @ formula-editor.min.js:1576
create @ formula-editor.min.js:1699
clickHandler @ formula-menu.conf.js:28
(匿名) @ wangEditor.min.js:1
formula-editor.min.js:1591 
        
       菜单名称重复:Trigonometric
_initMenuList @ formula-editor.min.js:1591
(匿名) @ formula-editor.min.js:1579
init @ formula-editor.min.js:1576
create @ formula-editor.min.js:1699
clickHandler @ formula-menu.conf.js:28
(匿名) @ wangEditor.min.js:1
formula-editor.min.js:1591 
        
       菜单名称重复:presets
_initMenuList @ formula-editor.min.js:1591
(匿名) @ formula-editor.min.js:1579
init @ formula-editor.min.js:1576
create @ formula-editor.min.js:1699
clickHandler @ formula-menu.conf.js:28
(匿名) @ wangEditor.min.js:1
formula-editor.min.js:1591 
        
       菜单名称重复:operators
_initMenuList @ formula-editor.min.js:1591
(匿名) @ formula-editor.min.js:1579
init @ formula-editor.min.js:1576
create @ formula-editor.min.js:1699
clickHandler @ formula-menu.conf.js:28
(匿名) @ wangEditor.min.js:1
formula-editor.min.js:1591 
        
       菜单名称重复:greekLetters
_initMenuList @ formula-editor.min.js:1591
(匿名) @ formula-editor.min.js:1579
init @ formula-editor.min.js:1576
create @ formula-editor.min.js:1699
clickHandler @ formula-menu.conf.js:28
(匿名) @ wangEditor.min.js:1
formula-editor.min.js:1591 
        
       菜单名称重复:inequation
_initMenuList @ formula-editor.min.js:1591
(匿名) @ formula-editor.min.js:1579
init @ formula-editor.min.js:1576
create @ formula-editor.min.js:1699
clickHandler @ formula-menu.conf.js:28
(匿名) @ wangEditor.min.js:1
formula-editor.min.js:1591 
        
       菜单名称重复:calculus
_initMenuList @ formula-editor.min.js:1591
(匿名) @ formula-editor.min.js:1579
init @ formula-editor.min.js:1576
create @ formula-editor.min.js:1699
clickHandler @ formula-menu.conf.js:28
(匿名) @ wangEditor.min.js:1
formula-editor.min.js:1591 
        
       菜单名称重复:arrows
_initMenuList @ formula-editor.min.js:1591
(匿名) @ formula-editor.min.js:1579
init @ formula-editor.min.js:1576
create @ formula-editor.min.js:1699
clickHandler @ formula-menu.conf.js:28
(匿名) @ wangEditor.min.js:1
formula-editor.min.js:1591 
        
       菜单名称重复:Trigonometric
_initMenuList @ formula-editor.min.js:1591
(匿名) @ formula-editor.min.js:1579
init @ formula-editor.min.js:1576
create @ formula-editor.min.js:1699
clickHandler @ formula-menu.conf.js:28
(匿名) @ wangEditor.min.js:1
formula-editor.min.js:1591 
        
       菜单名称重复:presets
_initMenuList @ formula-editor.min.js:1591
(匿名) @ formula-editor.min.js:1579
init @ formula-editor.min.js:1576
create @ formula-editor.min.js:1699
clickHandler @ formula-menu.conf.js:28
(匿名) @ wangEditor.min.js:1
formula-editor.min.js:1591 
        
       菜单名称重复:operators
_initMenuList @ formula-editor.min.js:1591
(匿名) @ formula-editor.min.js:1579
init @ formula-editor.min.js:1576
create @ formula-editor.min.js:1699
clickHandler @ formula-menu.conf.js:28
(匿名) @ wangEditor.min.js:1
formula-editor.min.js:1591 
        
       菜单名称重复:greekLetters
_initMenuList @ formula-editor.min.js:1591
(匿名) @ formula-editor.min.js:1579
init @ formula-editor.min.js:1576
create @ formula-editor.min.js:1699
clickHandler @ formula-menu.conf.js:28
(匿名) @ wangEditor.min.js:1
formula-editor.min.js:1591 
        
       菜单名称重复:inequation
_initMenuList @ formula-editor.min.js:1591
(匿名) @ formula-editor.min.js:1579
init @ formula-editor.min.js:1576
create @ formula-editor.min.js:1699
clickHandler @ formula-menu.conf.js:28
(匿名) @ wangEditor.min.js:1
formula-editor.min.js:1591 
        
       菜单名称重复:calculus
_initMenuList @ formula-editor.min.js:1591
(匿名) @ formula-editor.min.js:1579
init @ formula-editor.min.js:1576
create @ formula-editor.min.js:1699
clickHandler @ formula-menu.conf.js:28
(匿名) @ wangEditor.min.js:1
formula-editor.min.js:1591 
        
       菜单名称重复:arrows
_initMenuList @ formula-editor.min.js:1591
(匿名) @ formula-editor.min.js:1579
init @ formula-editor.min.js:1576
create @ formula-editor.min.js:1699
clickHandler @ formula-menu.conf.js:28
(匿名) @ wangEditor.min.js:1
formula-editor.min.js:1591 
        
       菜单名称重复:Trigonometric
_initMenuList @ formula-editor.min.js:1591
(匿名) @ formula-editor.min.js:1579
init @ formula-editor.min.js:1576
create @ formula-editor.min.js:1699
clickHandler @ formula-menu.conf.js:28
(匿名) @ wangEditor.min.js:1
formula-editor.min.js:1591 
        
       菜单名称重复:presets
_initMenuList @ formula-editor.min.js:1591
(匿名) @ formula-editor.min.js:1579
init @ formula-editor.min.js:1576
create @ formula-editor.min.js:1699
clickHandler @ formula-menu.conf.js:28
(匿名) @ wangEditor.min.js:1
formula-editor.min.js:1591 
        
       菜单名称重复:operators
_initMenuList @ formula-editor.min.js:1591
(匿名) @ formula-editor.min.js:1579
init @ formula-editor.min.js:1576
create @ formula-editor.min.js:1699
clickHandler @ formula-menu.conf.js:28
(匿名) @ wangEditor.min.js:1
formula-editor.min.js:1591 
        
       菜单名称重复:greekLetters
_initMenuList @ formula-editor.min.js:1591
(匿名) @ formula-editor.min.js:1579
init @ formula-editor.min.js:1576
create @ formula-editor.min.js:1699
clickHandler @ formula-menu.conf.js:28
(匿名) @ wangEditor.min.js:1
formula-editor.min.js:1591 
        
       菜单名称重复:inequation
_initMenuList @ formula-editor.min.js:1591
(匿名) @ formula-editor.min.js:1579
init @ formula-editor.min.js:1576
create @ formula-editor.min.js:1699
clickHandler @ formula-menu.conf.js:28
(匿名) @ wangEditor.min.js:1
formula-editor.min.js:1591 
        
       菜单名称重复:calculus
_initMenuList @ formula-editor.min.js:1591
(匿名) @ formula-editor.min.js:1579
init @ formula-editor.min.js:1576
create @ formula-editor.min.js:1699
clickHandler @ formula-menu.conf.js:28
(匿名) @ wangEditor.min.js:1
formula-editor.min.js:1591 
        
       菜单名称重复:arrows
_initMenuList @ formula-editor.min.js:1591
(匿名) @ formula-editor.min.js:1579
init @ formula-editor.min.js:1576
create @ formula-editor.min.js:1699
clickHandler @ formula-menu.conf.js:28
(匿名) @ wangEditor.min.js:1
formula-editor.min.js:1591 
        
       菜单名称重复:Trigonometric
_initMenuList @ formula-editor.min.js:1591
(匿名) @ formula-editor.min.js:1579
init @ formula-editor.min.js:1576
create @ formula-editor.min.js:1699
clickHandler @ formula-menu.conf.js:28
(匿名) @ wangEditor.min.js:1
formula-editor.min.js:1591 
        
       菜单名称重复:presets
_initMenuList @ formula-editor.min.js:1591
(匿名) @ formula-editor.min.js:1579
init @ formula-editor.min.js:1576
create @ formula-editor.min.js:1699
clickHandler @ formula-menu.conf.js:28
(匿名) @ wangEditor.min.js:1
formula-editor.min.js:1591 
        
       菜单名称重复:operators
_initMenuList @ formula-editor.min.js:1591
(匿名) @ formula-editor.min.js:1579
init @ formula-editor.min.js:1576
create @ formula-editor.min.js:1699
clickHandler @ formula-menu.conf.js:28
(匿名) @ wangEditor.min.js:1
formula-editor.min.js:1591 
        
       菜单名称重复:greekLetters
_initMenuList @ formula-editor.min.js:1591
(匿名) @ formula-editor.min.js:1579
init @ formula-editor.min.js:1576
create @ formula-editor.min.js:1699
clickHandler @ formula-menu.conf.js:28
(匿名) @ wangEditor.min.js:1
formula-editor.min.js:1591 
        
       菜单名称重复:inequation
_initMenuList @ formula-editor.min.js:1591
(匿名) @ formula-editor.min.js:1579
init @ formula-editor.min.js:1576
create @ formula-editor.min.js:1699
clickHandler @ formula-menu.conf.js:28
(匿名) @ wangEditor.min.js:1
formula-editor.min.js:1591 
        
       菜单名称重复:calculus
_initMenuList @ formula-editor.min.js:1591
(匿名) @ formula-editor.min.js:1579
init @ formula-editor.min.js:1576
create @ formula-editor.min.js:1699
clickHandler @ formula-menu.conf.js:28
(匿名) @ wangEditor.min.js:1
formula-editor.min.js:1591 
        
       菜单名称重复:arrows
_initMenuList @ formula-editor.min.js:1591
(匿名) @ formula-editor.min.js:1579
init @ formula-editor.min.js:1576
create @ formula-editor.min.js:1699
clickHandler @ formula-menu.conf.js:28
(匿名) @ wangEditor.min.js:1
formula-editor.min.js:1591 
        
       菜单名称重复:Trigonometric
_initMenuList @ formula-editor.min.js:1591
(匿名) @ formula-editor.min.js:1579
init @ formula-editor.min.js:1576
create @ formula-editor.min.js:1699
clickHandler @ formula-menu.conf.js:28
(匿名) @ wangEditor.min.js:1

```
点击已经插入的公式，也会报错：
```
Uncaught TypeError: t.className.split is not a function
    at x.hasClass (wangEditor.min.js:1:10871)
    at HTMLDivElement.<anonymous> (wangEditor.min.js:1:145768)
```

**Comment by hansonGong** [comment]
已经在示例中更新用法 https://codesandbox.io/s/funny-leaf-u9gso4?file=/src/utils/formula-menu-conf.js

**Comment by Joe4smu** [comment]
谢谢回复
点击已插入的公式时还是会报错，以下是示例中报错信息：

TypeError
elem.className.split is not a function
DomElement.hasClass
https://u9gso4.csb.app/node_modules/wangeditor/dist/wangEditor.js:834:30
HTMLDivElement.eval
https://u9gso4.csb.app/node_modules/wangeditor/dist/wangEditor.js:12082:19
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.
This error overlay is powered by `react-error-overlay` used in `create-react-app`.
